---
title: Your awesome title
timezone: UTC
collections:
  gallery:
    title: Gallery
    output: true
    permalink: gallery
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
url: http://jekyll.github.io
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
permalink: "/:year/:title:output_ext"
